### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by samvid2020** [Google-Developer-Students-Club-DMCE/Electric-Station-App-Hactoberfest-2022#1]
Splash Screen needs to be created until the user gets directed to the main Homepage 
@jaydip-pawar Can you assign this issue to me?

**Comment by jaydip-pawar** [comment]
Yes sure, start building a splash screen 👍

**Comment by axatabyss** [comment]
Hey @jaydip-pawar please assign this issue to me as no updates from @samvid2020 
Already created PR #5

**Comment by jaydip-pawar** [comment]
Ok @axatabyss, I'll assign this issue to you.

**Comment by jaydip-pawar** [comment]
> Hey @jaydip-pawar please assign this issue to me as no updates from @samvid2020 Already created PR #5

Hello @axatabyss, I'll assign this issue to you, but I was looking a splash screen without any external library, so I can't accept your current pull request. You can use the timer for splash screen to navigate from one screen to other in some time interval.

**Comment by axatabyss** [comment]
@jaydip-pawar Please check #9

**Comment by jaydip-pawar** [comment]
Threat is closed as issue is resolved.
